kind = "web"
previewPath = "/"
title = "EGRESANTOS — Ticketera"
version = "1.0.0"
id = "artifacts/egresantos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24282

[services.development]
run = "pnpm --filter @workspace/egresantos run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/egresantos", "run", "build" ]
publicDir = "artifacts/egresantos/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24282"
BASE_PATH = "/"
